### ISSUE TITLE
Naming structure of output files.

### ISSUE THREAD

**Issue by ChipoHankumbaMuleya** [verbal-autopsy-software/shinyVA#1]
I've noticed that the pdf files generated have generic names like 'plotAdult' or 'plotAgeDist', regardless of the algorith used. This means however that subsequent iterations of the analysis overwrites these files. I would suggest a naming structure that includes the name of the algorithm used as well as date and time of the job.

**Comment by jarathomas** [comment]
Good idea!  I just implemented this in the latest version of the shiny app.

Many thanks,
Jason
