### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ChipoHankumbaMuleya** [verbal-autopsy-software/shinyVA#3]
The program crashes with error:

Listening on http://127.0.0.1:5997
Warning: Error in formals: object 'map_records2' not found
  77: formals
  72: observeEventHandler [C:/VAProtocol/Shiny/shiny-openVA.R#259]
   1: runApp

**Comment by jarathomas** [comment]
I think you are using an outdated version of the shiny app.  Try the latest version and see if 
it gives you the same error.

**Comment by ChipoHankumbaMuleya** [comment]
I've updated to the latest version and InterVA5 runs without any errors. InsilicoVA 2016 gave me this error however before crashing;
'Warning: Error in insilico.fit: Not enough sample'.

The dataset has 43 cases.

**Comment by jarathomas** [comment]
Can you try the latest version of the shiny app, or send me a data file that produces the error?

**Comment by ChipoHankumbaMuleya** [comment]
Hi Jason,

 

I did this using the latest version. Please find attached the data file.

 

Thanks

**Comment by jarathomas** [comment]
Sorry for the silence on this -- I was not able to access the data file you attached; and sent a separate email to see if we could pass the file that way, but never heard back from you.  Are you still running
into this error?

**Comment by jarathomas** [comment]
We have recently done a major overhaul to the app, which addresses this issue.
